name: Release Gradle Plugin

on:
  workflow_dispatch:
    inputs:
      publishOnly:
        description: 'Only Publish the plugin to the Gradle Plugin Portal'
        required: false
        default: false
        type: boolean

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/wrapper-validation@v4
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew test

  determine-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: semantic_version
        uses: paulhatch/semantic-version@v5.4.0
    outputs:
      version: ${{ steps.semantic_version.outputs.version }}
      previous_version: ${{ steps.semantic_version.outputs.previous_version }}
      version_type: ${{ steps.semantic_version.outputs.version_type }}

  release:
    runs-on: ubuntu-latest
    needs: [ test, determine-version ]
    if: inputs.publishOnly == 'false' && needs.determine-version.outputs.version_type != 'none'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create new tagged release
        run: |
          # Set up Git user
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Update version in build.gradle.kts
          sed -i 's/version = ".*"/version = "${{ needs.determine-version.outputs.version }}"/' plugin/build.gradle.kts
          git add plugin/build.gradle.kts
          git commit -m "chore: bump version to ${{ needs.determine-version.outputs.version }}"
          git push origin main
          
          # Create a new tag
          git tag v${{ needs.determine-version.outputs.version }}
          git push origin v${{ needs.determine-version.outputs.version }}

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fromTag: v${{ needs.determine-version.outputs.version }}
          toTag: v${{ needs.determine-version.outputs.previous_version }}
          writeToFile: false

      - name: Generate GitHub Release Notes
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          tag: v${{ needs.determine-version.outputs.version }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/wrapper-validation@v4
      - uses: gradle/actions/setup-gradle@v4

      - name: Publish Plugin to Gradle Plugin Portal
        run: ./gradlew publishPlugins
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
